Repository mohit-kumar-sharma/proffer, pull requests merged in 2020-06, with the labels that each got.

#31 Add unit tests for aws common lib
  resources/aws/common/ami.go
  resources/aws/common/ami_test.go
  resources/aws/common/cases_test.go
  resources/aws/common/creds.go
  resources/aws/common/creds_test.go
  resources/aws/common/mock_test.go
  resources/aws/copyami/apply.go
  resources/aws/shareami/apply.go
  resources/aws/shareami/prepare.go
  vendor/github.com/aws/aws-sdk-go/service/ec2/ec2iface/interface.go
  vendor/modules.txt
Labels: tests

#33 Fix go report
  .codecov.yml
  .github/workflows/test.yml
  .golangci.yml
  .goreleaser.yml
  .pre-commit-config.yaml
  Makefile
  NOTICE.md
  README.md
  cmd/apply.go
  cmd/completion.go
  cmd/gendoc.go
  cmd/root.go
  cmd/validate.go
  command/plugin.go
  common/clogger/main.go
  common/validator/main.go
  components/resources.go
  examples/aws/share-ami/copy-and-sahre-ami-across-accounts.yml
  parser/parser.go
  parser/yaml.go
  quickstart-guide/copy.md
  quickstart-guide/install.md
  resources/README.md
  resources/aws/common/ami.go
  resources/aws/common/creds.go
  resources/aws/copyami/apply.go
  resources/aws/copyami/resource.go
  resources/aws/shareami/apply.go
  resources/aws/shareami/resource.go
  test/invalid_yml/sample2.yml
  test/invalid_yml/sample3.yml
  test/valid_config/dynamicproffer.yml
  test/valid_config/shareami.yml
  test/valid_yml/proffer.yml
  test/valid_yml/shareami.yml
Labels: documentation

#34 Add inventory support
  .gitignore
  .golangci.yml
  .pre-commit-config.yaml
  README.md
  cmd/apply.go
  cmd/gendoc.go
  components/resources.go
  doc/proffer.md
  doc/proffer_apply.md
  doc/proffer_completion.md
  doc/proffer_gendoc.md
  doc/proffer_validate.md
  examples/aws/share-ami/copy-and-sahre-ami-across-accounts.yml
  images/proffer-workflow.png
  output-samples/example-inventory.yml
  quickstart-guide/share.md
  resources/README.md
  resources/aws/common/creds.go
  resources/aws/common/creds_test.go
  resources/aws/common/mock_test.go
  resources/aws/copyami/apply.go
  resources/aws/copyami/resource.go
  resources/aws/shareami/README.md
  resources/aws/shareami/apply.go
  resources/aws/shareami/prepare.go
  resources/aws/shareami/resource.go
  test/valid_config/data.yml
  test/valid_config/dynamicproffer.yml
  vendor/github.com/aws/aws-sdk-go/service/iam/api.go
  vendor/github.com/aws/aws-sdk-go/service/iam/doc.go
  vendor/github.com/aws/aws-sdk-go/service/iam/errors.go
  vendor/github.com/aws/aws-sdk-go/service/iam/iamiface/interface.go
  vendor/github.com/aws/aws-sdk-go/service/iam/service.go
  vendor/github.com/aws/aws-sdk-go/service/iam/waiters.go
  vendor/modules.txt
Labels: documentation, enhancement
